version: '3.5'
services:
  backend-api:
    build:
      context: ./backend-api
      target: build
    volumes:
      - ./backend-api:/go/app
    command: ["realize", "start", "--run"]
    # command: ["sleep", "6000000"]
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    ports:
      - 8081:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: ["npm", "run", "serve"]
    #command: ["sleep", "6000000"]
