version: '3'
services:
  backend-api:
    build: ./backend-api
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - 8081:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: ["npm", "run", "serve"]
#    command: ["sleep", "6000000"]
